variable "nw_name" { default = "test" }
variable "auto_create_subnetworks" {default = "false"}
variable "project"{ default = "project" }
variable "ins_name"{default = "test"}
variable "machine_type" {default = "f1-micro"}
variable "zone" {default = "us-west2-a"}
variable "sbnt_name"{default = "ts-1"}
variable "cidr"{default = "192.168.10.0/24"}
variable "sbnt_region"{default ="us-west2"}
variable "fw_name"{default ="test"}
